fragment NotificationAttributes on Notification {
    from {
        _id
        name
        type
    }

    to {
        _id
        name
        type
    }

    _id
    name
    type
    status
    description
    createdBy
    createdAt
    updatedBy
    updatedAt

    Files {
        _id
        name
        localUrl
        cloudUrl
        size
        mimeType
        type
        status
    }

    histories {
        party {
            _id
            type
            name
        }
        description
        timestamp
    }
}
