fragment FileAttributes on File {
    fsUrl
    localUrl
    cloudUrl
    size
    mimeType

    _id
    name
    type
    status
    description
    createdBy
    createdAt
    updatedBy
    updatedAt

    histories {
        party {
            _id
            type
            name
        }
        description
        timestamp
    }
}
