fragment CounterAttributes on Counter {
    counter

    _id
    name
    type
    status
    description
    createdBy
    createdAt
    updatedBy
    updatedAt

    histories {
        party {
            _id
            type
            name
        }
        description
        timestamp
    }
}
